### PR TITLE
Added comments, optional java install, logstash_custom_outputs, fix on permissions, java default to 8 due to logstash 5.x requirement

### PR DESCRIPTION
**Pull request by pablodav**
* Added optional java install
* changed default java to 8 when possible (logstash 5.x doesn't works with java 7)
* Added comments for templates base
* Added logstash_custom_outputs:
* fix on permissions
* removed validate due to issues with ansible

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@pablodav Thanks for the PR. I will look this over in the next few days and provide some feedback prior to merging. Much appreciated for sure!

**Comment by pablodav** [comment]
Just for your information, In my case I use logstash with graylog2 too, so it's better to manage the installation of java on separate role, the result on my playbook calling roles is: 

```
- name: Add java-jdk-8 ppa for Ubuntu trusty
  hosts: graylog2_servers
  become: yes
  environment: "{{ proxy_env }}"

  tasks:
    - name: installing repo for Java 8 in Ubuntu 14.04
      apt_repository: repo='ppa:openjdk-r/ppa'
      when: ansible_distribution_release == 'trusty'

- name: Apply roles for graylog2 servers
  hosts: graylog2_servers
  become: yes
  environment: "{{ proxy_env }}"

  roles:

    - role: lesmyrmidons.mongodb
      tags:
        - role::mongodb
        - graylog2_servers

    - role: geerlingguy.java
      when: ansible_distribution_release == 'trusty'
      java_packages:
        - openjdk-8-jdk

      tags:
        - role::elasticsearch
        - graylog2_servers

    - role: elastic.elasticsearch
      tags:
        - role::elasticsearch
        - graylog2_servers

    - role: jdauphant.nginx
      tags:
        - role::nginx
        - graylog2_servers

    - role: graylog2.graylog
      tags:
        - role::graylog
        - graylog2_servers

    - role: ansible-logstash
      tags:
        - role::logstash
        - graylog2_servers
```

And for best practices the vars that specify the es_version, password, logstash vars, graylog2 vars, etc are all in my group_vars/group/vars.

In the case of this usage I have also updated the graylog2 readme and it is on main role: 
https://github.com/Graylog2/graylog-ansible-role#explicit-playbook-of-roles 

For that reason is good to have these optional vars in logstash role too.

Kind regards,
Pablo.

**Comment by mrlesmithjr** [comment]
@pablodav Merged. Thanks for this!

**Comment by pablodav** [comment]
Thanks for merging, incluso have more improvements that Will make New pull
request soon.

Kind regards.

**Comment by mrlesmithjr** [comment]
@pablodav Sounds great! Thanks!

**Pull request merged**
