### PR TITLE
enable settings to work behind proxy with auth

### PR DESCRIPTION
**Pull request by pablodav**
Something changed in latest versions of logstash that broke installing plugins behind authenticated proxies in same way as it was working before. 
Now checking https://github.com/elastic/logstash/issues/6528 I have found additional vars to add in command line that makes it work again. 

These changes adds the option to get it working on such special scenarios (normal on many enterprises).

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
How does this affect scenarios where a non auth proxy is in use or no proxy at all?

**Comment by pablodav** [comment]
Shouldn't afffect at all, as you can see the default var is without proxy settings: 

```yaml
logstash_plugin_cmd_vars: "JARS_SKIP='true'"
```

And there is only a commented line with the optional var to setup proxy, the full change in `defaults/main.yml`: 

```yaml
# https://github.com/elastic/logstash/issues/6528
logstash_plugin_cmd_vars: "JARS_SKIP='true'"
# Other examples:
# Options to work with proxy
# logstash_plugin_cmd_vars: "JARS_SKIP='true' JRUBY_OPTS='-J-Dhttps.proxyHost=user:password@proxy.com -J-Dhttps.proxyPort=8080 -J-Dhttp.proxyHost=user:password@proxy.com -J-Dhttp.proxyPort=8080'" 
```

So for those that require proxy settings, only needs to add the var on their `hosts_vars/group_vars` file: 

```yaml
logstash_plugin_cmd_vars: "JARS_SKIP='true' JRUBY_OPTS='-J-Dhttps.proxyHost=user:password@proxy.com -J-Dhttps.proxyPort=8080 -J-Dhttp.proxyHost=user:password@proxy.com -J-Dhttp.proxyPort=8080'" 
```

**Comment by mrlesmithjr** [comment]
perfect!

**Comment by mrlesmithjr** [comment]
merged! Thanks for the contribution again man.

**Comment by pablodav** [comment]
Welcome! thanks for merging too!

**Pull request merged**
